apiVersion: v1
kind: Namespace
metadata:
  name: prod


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: prod
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: "rajhisaifeddine/demo:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: prod
  labels:
    app: demo
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
  - port: 8088
    targetPort: 8080
    protocol: TCP

